### PR TITLE
Adding Windows CI

### PR DESCRIPTION
**Pull request by brianmichel**
We want to setup Windows CI for all of the Pointfree repos that are used in TCA to ensure that we have cross platform compatibility going forward (or at least to ensure that nothing breaks).

### CODE REVIEW

**Comment by brianmichel** [comment]
All of these tests currently pass on Windows!

**Comment by brianmichel** [comment]
Ran these tests locally with the 5.8.1 toolchain which is the most non-development current toolchain and everything seems to pass there so I bumped the config to that.

**Comment by mbrandonw** [comment]
Hi @brianmichel, thanks for this! If you can't figure out why 5.8.1 is still failing on CI, feel free to bump to 5.9 if that gets things passing.

**Comment by brianmichel** [comment]
@mbrandonw yeah it's on my list this week, just getting sidetracked by some C++ Interop stuff that's blocking our project which took precedence. 🤞 it's an easy fix to get this to pass!

**Comment by brianmichel** [comment]
Hey @mbrandonw looks like there was some bug preventing running the tests in a release config, so I've broken out the build phases and the test phases to try to get a good balance of coverage on the profiles.

**Comment by brianmichel** [comment]
@mbrandonw looks like this should be good now, had to make a couple adjustments but left comments where I did

**Review by mbrandonw — APPROVED** [review]
Hi @brianmichel looks great, thanks for figuring out the edge cases! Once Swift 5.9 is available on Windows we can revisit bringing back release testing too.

**Pull request merged**
