### PR TITLE
Compile for Android

### PR DESCRIPTION
**Pull request by johankool**
Compile with 

```
OMIT_MACRO_TESTS=1 /Library/Developer/Toolchains/swift-6.0.2-RELEASE.xctoolchain/usr/bin/swift build --swift-sdk aarch64-unknown-linux-android24 --build-tests
```

Copy to Android device

Run with

```
./swift-case-pathsPackageTests.xctest
```

### CODE REVIEW

**Comment by stephencelis** [comment]
@johankool Thanks for this! We'd love to ensure we don't break it in the future, though. Do you think it's possible to add Android CI to this repo and others that you help get compiling?

**Comment by johankool** [comment]
@stephencelis I'll take a look what that would take with GitHub Actions. I suppose we could run the tests in an Android emulator.

**Comment by johankool** [comment]
@stephencelis Got it working on CI for Android. Currently running the full CI workflow [here](https://github.com/johankool/swift-case-paths/actions/runs/12213034108).

**Comment by stephencelis** [comment]
Awesome, thanks!

**Pull request merged**
