### PR TITLE
Export CasePathsMacros

### PR DESCRIPTION
**Pull request by ImSingee**

### CODE REVIEW

**Comment by mbrandonw** [comment]
Hi @ImSingee, can you explain a bit why you need access to the `CasePathMacros` module? Are you building a tool that uses the various macro conformances somehow? And if so, can you share more details?

We would be happy to publicize this module if it's useful. We just aren't aware of any actual uses for it.

**Comment by ImSingee** [comment]
@mbrandonw Ah I just think it's necessary.

I can't use `@CasePathable` macros... It always show an error `External macro implementation type 'CasePathsMacros.CasePathableMacro' could not be found for macro 'CasePathable()'`

**Comment by mbrandonw** [comment]
That should work fine. There's no need to publicize the macros module. Can you share a minimal reproducing project that demonstrates the behavior you are seeing?

**Comment by ImSingee** [comment]
@mbrandonw So strange😂 I just remove my xcuserdata and then it works.

Sorry for wasting your time...

**Pull request closed without merging**
