### PR TITLE
CocoaPods Support

### PR DESCRIPTION
**Pull request by AdiAyyakad**
Love the pod and usage of it! Just wanted to create a quick little podspec so others can use it easily too :)

Please feel free to edit the authors and stuff I have it all pointed to my fork for now, but obviously would love it to just be part of this module as a first party thing.

### CODE REVIEW

**Comment by stephencelis** [comment]
Hey @AdiAyyakad! Thanks for taking the time to PR!

Could you look over the discussion at #2 to let us know if we're missing anything? It seems like CocoaPods support isn't necessary for this kind of library these days as SPM is an alternative.

**Comment by AdiAyyakad** [comment]
Ahh I just read through that. I think it's really just as you noted option 2 where we have one dependency manager and don't want to use two. It's not a dealbreaker and honestly I've never used SPM in the past, so perhaps worth trying. We're just not going away from Objective-C in some of our codebase + dependencies anytime soon so doesn't seem worthwhile to invest in multiple dependency managers; especially when adding cocoapod support to another library is super simple as you can see. Not saying it's necessarily something pointfree needs to invest in - luckily that's the beauty of opensource :)

**Comment by stephencelis** [comment]
Since SPM is built into Xcode we think it's a bit safer to get behind. And I definitely encourage you to give it a shot! It's pretty nice these days 😄

I'll keep this PR available for a bit in case we get more motivation discussed in #2, though!

**Comment by AdiAyyakad** [comment]
Ahh so one thing I didn't note was that we're doing some version of composable architecture, definitely with less structure than your implementation (which has been so cool watching unfold!). However, we've already invested kind of heavily in doing it all via Cocoapods using pods and subspecs to build and distribute the modules internally. Without totally retooling, we actually need to use this spec ☝️ to even bring in CasePaths to our modules. Again, definitely the grave we've dug for ourselves but it is a big enough reason and again reasonable for anyone who doesn't have 100% swift dependencies like us.

**Comment by ixrevo** [comment]
The problem with SPM arises when you have multiple transitive dependencies because SPM integrates its modules as static libraries. For example, I can't create an SPM module with ComposableArchitectre adapted to RxSwift, because
App -> RxDataSources
RxDataSources -> RxSwift
App -> RxComposableArchitecture
RxComposableArchitecture -> RxSwift
and I got two copies of RxSwift in the app. I was unsuccessful in finding a workaround for this problem. The support of Cocoapods would help.

**Comment by AdiAyyakad** [comment]
@ixrevo I do have a working podspec up at `http://github.com/AdiAyyakad/swift-case-paths` if you want to just point to master directly 🤷‍♂ that's what we've been doing - would still be nice to get this in the main repo but it hasn't been a blocker for us

**Comment by stephencelis** [comment]
@ixrevo I believe this is a bug with Xcode 11.4 :( 11.3 didn't have this problem. I've filed feedback with Apple but feel free to dupe!

**Pull request closed without merging**
